version: '3.8'

services:
  chatbot:
    build: .
    container_name: chatbot-service
    ports:
      - '4000:4000'
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - '6379:6379'
